apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
spec:
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: atomycloud/solar-system
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: solar-system
spec:
  selector:
    app: solar-system
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
